field.formatter.settings.text_with_title_tabs_vertical_formatter:
  type: mapping
  label: 'Tabs layout'
  mapping:
    tabs_width:
      type: string
      label: 'Text Length'
    only_one_open:
      type: bool
      label: 'Only one open - similar to traditional accordion behavior'